# Generated by Django 4.1.1 on 2022-10-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
