# Generated by Django 4.1.1 on 2022-10-04 10:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=user.models.image_location),
        ),
    ]
